 # Paths to user settings for latexindent.pl
 #
 # Note that the settings will be read in the order you
 # specify here- each successive settings file will overwrite
 # the variables that you specify

 paths:
 - /Users/u300509/git/config_files/latexindentSettings.yaml
